version: '3.8'

services:
  training:
    image: projeto-final-rl:latest
    command: python main.py
    volumes:
      - ./main.py:/app/main.py
      - ./replay.py:/app/replay.py
      - ./smpe.py:/app/smpe.py
      - ./src:/app/src
      - ./configs:/app/configs
      - ./progress:/app/progress
      - ./results:/app/results
      - ./videos:/app/videos
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  replay:
    image: projeto-final-rl:latest
    command: python replay.py
    volumes:
      - ./main.py:/app/main.py
      - ./replay.py:/app/replay.py
      - ./src:/app/src
      - ./configs:/app/configs
      - ./progress:/app/progress
      - ./results:/app/results
      - ./videos:/app/videos
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
